# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website2', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_text', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='Contestants',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RenameField(
            model_name='contestants',
            old_name='choice_text',
            new_name='contestant_name',
        ),
        migrations.RemoveField(
            model_name='contestants',
            name='question',
        ),
        migrations.AddField(
            model_name='contestants',
            name='position',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='website2.Position'),
            preserve_default=False,
        ),
    ]
